builds:
- goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64

archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'

nfpms:
  - formats:
      - deb
      - rpm
